org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=dsbr
mod_group=top.wu949.dsbr
mod_version=0.1.23
mod_name=Dragon Survival Bedrock Renderer
mod_authors=wuhanhao\u548CGPT-5.4(Codex)
mod_license=MIT

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1]

neo_version=21.1.213
neo_version_range=[21.1.186,)
loader_version_range=[3,)

pack_format_number=48
