modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
    Experimental client-side renderer backend for Dragon Survival.
    Bedrock mode renders dragon forms with a custom BedrockPart pipeline.
    YSM mode keeps the local player on the player render path while other players and external dragon renders continue using the Bedrock backend.
    '''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "dragonsurvival"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "${mod_id}.mixins.json"